name: Terraform Deploy
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.5

    - name: Test AWS Credentials avec AWS CLI
      run: |
        echo "AWS_ACCESS_KEY_ID starts with: ${AWS_ACCESS_KEY_ID:0:4}..."
        echo "AWS_SECRET_ACCESS_KEY length: ${#AWS_SECRET_ACCESS_KEY}"
        aws --version
        aws sts get-caller-identity
        aws configure list
    
    - name: Terraform Init
      run: terraform init        

#    Pose problème lors de l'exécution de l'action : "Error: Terraform exited with code 3."    
#    - name: Terraform Format Check
#      run: terraform fmt -check

    - name: Terraform Format write
      run: terraform fmt -write

    - name: Show formatted main.tf
      run: cat main.tf

    - name: Terraform Validate
      run: terraform validate
    
    - name: Terraform Plan
      id: plan
      run: |                        
        terraform plan -no-color -out=tfplan
        
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply tfplan
